// Code generated by qtc from "filelist.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line internal/templates/filelist.qtpl:3
package templates

//line internal/templates/filelist.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/filelist.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/filelist.qtpl:4
type FileListPage struct {
	Files []map[string]string
}

//line internal/templates/filelist.qtpl:10
func (p *FileListPage) StreamHead(qw422016 *qt422016.Writer) {
//line internal/templates/filelist.qtpl:10
	qw422016.N().S(`
<head>
    <title>File browsing</title>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="../../assets/css/filelist.css">
    <link rel="icon" href="data:,">
</head>
`)
//line internal/templates/filelist.qtpl:19
}

//line internal/templates/filelist.qtpl:19
func (p *FileListPage) WriteHead(qq422016 qtio422016.Writer) {
//line internal/templates/filelist.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/filelist.qtpl:19
	p.StreamHead(qw422016)
//line internal/templates/filelist.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/filelist.qtpl:19
}

//line internal/templates/filelist.qtpl:19
func (p *FileListPage) Head() string {
//line internal/templates/filelist.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/filelist.qtpl:19
	p.WriteHead(qb422016)
//line internal/templates/filelist.qtpl:19
	qs422016 := string(qb422016.B)
//line internal/templates/filelist.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/filelist.qtpl:19
	return qs422016
//line internal/templates/filelist.qtpl:19
}

//line internal/templates/filelist.qtpl:21
func (p *FileListPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/templates/filelist.qtpl:21
	qw422016.N().S(`
`)
//line internal/templates/filelist.qtpl:22
	streamlistFiles(qw422016, p.Files)
//line internal/templates/filelist.qtpl:22
	qw422016.N().S(`
`)
//line internal/templates/filelist.qtpl:23
}

//line internal/templates/filelist.qtpl:23
func (p *FileListPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/templates/filelist.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/filelist.qtpl:23
	p.StreamBody(qw422016)
//line internal/templates/filelist.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/filelist.qtpl:23
}

//line internal/templates/filelist.qtpl:23
func (p *FileListPage) Body() string {
//line internal/templates/filelist.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/filelist.qtpl:23
	p.WriteBody(qb422016)
//line internal/templates/filelist.qtpl:23
	qs422016 := string(qb422016.B)
//line internal/templates/filelist.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/filelist.qtpl:23
	return qs422016
//line internal/templates/filelist.qtpl:23
}

//line internal/templates/filelist.qtpl:25
func streamval(qw422016 *qt422016.Writer, key string, arr map[string]string) {
//line internal/templates/filelist.qtpl:25
	qw422016.N().S(`
    `)
//line internal/templates/filelist.qtpl:26
	if arr[key] != "" {
//line internal/templates/filelist.qtpl:26
		qw422016.N().S(`
        `)
//line internal/templates/filelist.qtpl:27
		qw422016.E().S(arr[key])
//line internal/templates/filelist.qtpl:27
		qw422016.N().S(`
    `)
//line internal/templates/filelist.qtpl:28
	}
//line internal/templates/filelist.qtpl:28
	qw422016.N().S(`
`)
//line internal/templates/filelist.qtpl:29
}

//line internal/templates/filelist.qtpl:29
func writeval(qq422016 qtio422016.Writer, key string, arr map[string]string) {
//line internal/templates/filelist.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/filelist.qtpl:29
	streamval(qw422016, key, arr)
//line internal/templates/filelist.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/filelist.qtpl:29
}

//line internal/templates/filelist.qtpl:29
func val(key string, arr map[string]string) string {
//line internal/templates/filelist.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/filelist.qtpl:29
	writeval(qb422016, key, arr)
//line internal/templates/filelist.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/templates/filelist.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/filelist.qtpl:29
	return qs422016
//line internal/templates/filelist.qtpl:29
}

//line internal/templates/filelist.qtpl:31
func streamlistFiles(qw422016 *qt422016.Writer, files []map[string]string) {
//line internal/templates/filelist.qtpl:31
	qw422016.N().S(`
<table>
    <thead>
    <tr class="header" id="theader">
        <th id="nameColumnHeader" tabindex=0 role="button">Name</th>
        <th id="sizeColumnHeader" class="detailsColumn" tabindex=0 role="button">
            Size
        </th>
        <th id="typeColumnHeader" class="detailsColumn" tabindex=0 role="button">
            Type
        </th>
    </tr>
    <tbody id="tbody">
    `)
//line internal/templates/filelist.qtpl:44
	for _, v := range files {
//line internal/templates/filelist.qtpl:44
		qw422016.N().S(`
    <tr>
        <td data-value="eblo_antona">
            <a class="icon-file" draggable="true" href='`)
//line internal/templates/filelist.qtpl:47
		streamval(qw422016, "id", v)
//line internal/templates/filelist.qtpl:47
		qw422016.N().S(`'>`)
//line internal/templates/filelist.qtpl:47
		streamval(qw422016, "name", v)
//line internal/templates/filelist.qtpl:47
		qw422016.N().S(`</a>
        </td>
        <!-- TODO -h size display MB,KB,GB -->
        <td class="detailsColumn" data-value='`)
//line internal/templates/filelist.qtpl:50
		streamval(qw422016, "size", v)
//line internal/templates/filelist.qtpl:50
		qw422016.N().S(`'>`)
//line internal/templates/filelist.qtpl:50
		streamval(qw422016, "size", v)
//line internal/templates/filelist.qtpl:50
		qw422016.N().S(`</td>
        <td class="detailsColumn" data-value='`)
//line internal/templates/filelist.qtpl:51
		streamval(qw422016, "type", v)
//line internal/templates/filelist.qtpl:51
		qw422016.N().S(`'>`)
//line internal/templates/filelist.qtpl:51
		streamval(qw422016, "type", v)
//line internal/templates/filelist.qtpl:51
		qw422016.N().S(`</td>
    </tr>
    </tbody>
    `)
//line internal/templates/filelist.qtpl:54
	}
//line internal/templates/filelist.qtpl:54
	qw422016.N().S(`
    </thead>
</table>
`)
//line internal/templates/filelist.qtpl:57
}

//line internal/templates/filelist.qtpl:57
func writelistFiles(qq422016 qtio422016.Writer, files []map[string]string) {
//line internal/templates/filelist.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/filelist.qtpl:57
	streamlistFiles(qw422016, files)
//line internal/templates/filelist.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/filelist.qtpl:57
}

//line internal/templates/filelist.qtpl:57
func listFiles(files []map[string]string) string {
//line internal/templates/filelist.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/filelist.qtpl:57
	writelistFiles(qb422016, files)
//line internal/templates/filelist.qtpl:57
	qs422016 := string(qb422016.B)
//line internal/templates/filelist.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/filelist.qtpl:57
	return qs422016
//line internal/templates/filelist.qtpl:57
}
