// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.

//line internal/templates/login.qtpl:2
package templates

//line internal/templates/login.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/login.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/login.qtpl:3
type Login struct {
	CsrfToken string
}

//line internal/templates/login.qtpl:9
func (p *Login) StreamHead(qw422016 *qt422016.Writer) {
//line internal/templates/login.qtpl:9
	qw422016.N().S(`
<head>
    <!-- TODO replace w/ asset directory provided by handler or whatever -->
    <!--  also add integrity check during application start(bootstrap) -->
    <link rel="stylesheet" href="../../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/css/login.css">
    <script type="text/javascript" src="../../assets/js/jquery-3.7.1.min.js"></script>
    <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgo=">
</head>
`)
//line internal/templates/login.qtpl:18
}

//line internal/templates/login.qtpl:18
func (p *Login) WriteHead(qq422016 qtio422016.Writer) {
//line internal/templates/login.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/login.qtpl:18
	p.StreamHead(qw422016)
//line internal/templates/login.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/login.qtpl:18
}

//line internal/templates/login.qtpl:18
func (p *Login) Head() string {
//line internal/templates/login.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/login.qtpl:18
	p.WriteHead(qb422016)
//line internal/templates/login.qtpl:18
	qs422016 := string(qb422016.B)
//line internal/templates/login.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/login.qtpl:18
	return qs422016
//line internal/templates/login.qtpl:18
}

//line internal/templates/login.qtpl:20
func (p *Login) StreamBody(qw422016 *qt422016.Writer) {
//line internal/templates/login.qtpl:20
	qw422016.N().S(`

<main class="form-signin w-100 m-auto">
    <form id="form" action="/auth" method="POST">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating">
            <input type="text" name="username" class="form-control" id="username" placeholder="username">
            <label for="username">Username</label>
        </div>
        <div class="form-floating">
            <input name="password" type="password" class="form-control" id="password" placeholder="Password">
            <label for="password">Password</label>
        </div>

        <div class="form-check text-start my-3">
            <input class="form-check-input" type="checkbox" value="remember-me" id="remember">
            <label class="form-check-label" for="remember">
                Remember me
            </label>
        </div>
        <button id="submit" class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
        <input type="hidden" name="csrf" value="`)
//line internal/templates/login.qtpl:42
	qw422016.E().S(p.CsrfToken)
//line internal/templates/login.qtpl:42
	qw422016.N().S(`"/>
    </form>
</main>
<script src="../../assets/js/bootstrap.bundle.min.js"></script>
<script>
    $('#submit').click( function(e) {
        //e.preventDefault()
        $('#form').submit();
    });
    /*
        $.post({
            url: '/auth',
            type: 'POST',
            data: $('#form').serialize(),
            success: function(data) {
                if (data.redirect) {
                    // data.redirect contains the string URL to redirect to
                    // window.location.href = data.redirect;
                    window.location.replace(data.redirect);
                }
            }
        });
    });*/
</script>
`)
//line internal/templates/login.qtpl:66
}

//line internal/templates/login.qtpl:66
func (p *Login) WriteBody(qq422016 qtio422016.Writer) {
//line internal/templates/login.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/login.qtpl:66
	p.StreamBody(qw422016)
//line internal/templates/login.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/login.qtpl:66
}

//line internal/templates/login.qtpl:66
func (p *Login) Body() string {
//line internal/templates/login.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/login.qtpl:66
	p.WriteBody(qb422016)
//line internal/templates/login.qtpl:66
	qs422016 := string(qb422016.B)
//line internal/templates/login.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/login.qtpl:66
	return qs422016
//line internal/templates/login.qtpl:66
}
