// Code generated by qtc from "otp.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.

//line internal/templates/otp.qtpl:2
package templates

//line internal/templates/otp.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/otp.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/otp.qtpl:3
type Otp struct {
}

//line internal/templates/otp.qtpl:8
func (p *Otp) StreamHead(qw422016 *qt422016.Writer) {
//line internal/templates/otp.qtpl:8
	qw422016.N().S(`
<!-- // video[path|type]string -->
<head>
    <!-- TODO replace w/ asset directory provided by handler or whatever -->
    <!--  also add integrity check during application start(bootstrap) -->
    <link rel="icon" href="data:,">
</head>
`)
//line internal/templates/otp.qtpl:15
}

//line internal/templates/otp.qtpl:15
func (p *Otp) WriteHead(qq422016 qtio422016.Writer) {
//line internal/templates/otp.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/otp.qtpl:15
	p.StreamHead(qw422016)
//line internal/templates/otp.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/otp.qtpl:15
}

//line internal/templates/otp.qtpl:15
func (p *Otp) Head() string {
//line internal/templates/otp.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/otp.qtpl:15
	p.WriteHead(qb422016)
//line internal/templates/otp.qtpl:15
	qs422016 := string(qb422016.B)
//line internal/templates/otp.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/otp.qtpl:15
	return qs422016
//line internal/templates/otp.qtpl:15
}

//line internal/templates/otp.qtpl:17
func (p *Otp) StreamBody(qw422016 *qt422016.Writer) {
//line internal/templates/otp.qtpl:17
	qw422016.N().S(`

`)
//line internal/templates/otp.qtpl:19
}

//line internal/templates/otp.qtpl:19
func (p *Otp) WriteBody(qq422016 qtio422016.Writer) {
//line internal/templates/otp.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/otp.qtpl:19
	p.StreamBody(qw422016)
//line internal/templates/otp.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/otp.qtpl:19
}

//line internal/templates/otp.qtpl:19
func (p *Otp) Body() string {
//line internal/templates/otp.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/otp.qtpl:19
	p.WriteBody(qb422016)
//line internal/templates/otp.qtpl:19
	qs422016 := string(qb422016.B)
//line internal/templates/otp.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/otp.qtpl:19
	return qs422016
//line internal/templates/otp.qtpl:19
}
