// Code generated by qtc from "rendernojs.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.

//line internal/templates/rendernojs.qtpl:2
package templates

//line internal/templates/rendernojs.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/rendernojs.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/rendernojs.qtpl:3
type RenderNoJs struct {
	File map[string]string
}

//line internal/templates/rendernojs.qtpl:9
func (p *RenderNoJs) StreamHead(qw422016 *qt422016.Writer) {
//line internal/templates/rendernojs.qtpl:9
	qw422016.N().S(`
<!-- // video[path|type]string -->
<head>
    <!-- TODO replace w/ asset directory provided by handler or whatever -->
    <!--  also add integrity check during application start(bootstrap) -->
    <link rel="icon" href="data:,">
</head>
`)
//line internal/templates/rendernojs.qtpl:16
}

//line internal/templates/rendernojs.qtpl:16
func (p *RenderNoJs) WriteHead(qq422016 qtio422016.Writer) {
//line internal/templates/rendernojs.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/rendernojs.qtpl:16
	p.StreamHead(qw422016)
//line internal/templates/rendernojs.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/rendernojs.qtpl:16
}

//line internal/templates/rendernojs.qtpl:16
func (p *RenderNoJs) Head() string {
//line internal/templates/rendernojs.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/rendernojs.qtpl:16
	p.WriteHead(qb422016)
//line internal/templates/rendernojs.qtpl:16
	qs422016 := string(qb422016.B)
//line internal/templates/rendernojs.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/rendernojs.qtpl:16
	return qs422016
//line internal/templates/rendernojs.qtpl:16
}

//line internal/templates/rendernojs.qtpl:18
func (p *RenderNoJs) StreamBody(qw422016 *qt422016.Writer) {
//line internal/templates/rendernojs.qtpl:18
	qw422016.N().S(`
<div id="player-container" class="h-box">
    <video style="outline:none;width:100%;background-color:#000" playsinline poster="../../assets/images/cinema_image.png"
           id="player" class="on-video_player video-js player-style-invidious"
           autoplay
           controls>
        <source src='stream/`)
//line internal/templates/rendernojs.qtpl:24
	qw422016.E().S(p.File["name"])
//line internal/templates/rendernojs.qtpl:24
	qw422016.N().S(`' type='`)
//line internal/templates/rendernojs.qtpl:24
	qw422016.E().S(p.File["type"])
//line internal/templates/rendernojs.qtpl:24
	qw422016.N().S(`' hidequalityoption="true" selected="true">
        <!-- TODO subtitles -->
        <!-- <track kind="captions" src="/api/v1/captions/RzzDuu1IgjM?label=English (auto-generated)&hmac_key=735e9ec6ce182ad1ebcc47f1899785d098c60eb4" label="English (auto-generated)"> -->
    </video>
</div>
`)
//line internal/templates/rendernojs.qtpl:29
}

//line internal/templates/rendernojs.qtpl:29
func (p *RenderNoJs) WriteBody(qq422016 qtio422016.Writer) {
//line internal/templates/rendernojs.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/rendernojs.qtpl:29
	p.StreamBody(qw422016)
//line internal/templates/rendernojs.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/rendernojs.qtpl:29
}

//line internal/templates/rendernojs.qtpl:29
func (p *RenderNoJs) Body() string {
//line internal/templates/rendernojs.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/rendernojs.qtpl:29
	p.WriteBody(qb422016)
//line internal/templates/rendernojs.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/templates/rendernojs.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/rendernojs.qtpl:29
	return qs422016
//line internal/templates/rendernojs.qtpl:29
}
