// Code generated by qtc from "totp.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/totp.qtpl:1
package templates

//line internal/templates/totp.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/totp.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/totp.qtpl:2
type Totp struct {
	CsrfToken string
}

//line internal/templates/totp.qtpl:8
func (p *Totp) StreamHead(qw422016 *qt422016.Writer) {
//line internal/templates/totp.qtpl:8
	qw422016.N().S(`
<head>
    <!-- TODO replace w/ asset directory provided by handler or whatever -->
    <!--  also add integrity check during application start(bootstrap) -->
    <link rel="stylesheet" href="../../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/css/totp.css">
    <script type="text/javascript" src="../../assets/js/jquery-3.7.1.min.js"></script>
    <link rel="icon" href="data:,">
</head>
`)
//line internal/templates/totp.qtpl:17
}

//line internal/templates/totp.qtpl:17
func (p *Totp) WriteHead(qq422016 qtio422016.Writer) {
//line internal/templates/totp.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/totp.qtpl:17
	p.StreamHead(qw422016)
//line internal/templates/totp.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/totp.qtpl:17
}

//line internal/templates/totp.qtpl:17
func (p *Totp) Head() string {
//line internal/templates/totp.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/totp.qtpl:17
	p.WriteHead(qb422016)
//line internal/templates/totp.qtpl:17
	qs422016 := string(qb422016.B)
//line internal/templates/totp.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/totp.qtpl:17
	return qs422016
//line internal/templates/totp.qtpl:17
}

//line internal/templates/totp.qtpl:19
func (p *Totp) StreamBody(qw422016 *qt422016.Writer) {
//line internal/templates/totp.qtpl:19
	qw422016.N().S(`

<main class="form-signin w-100 m-auto">
    <form id="form" action="/verify" method="POST">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating">
            <input type="number" name="code" class="form-control" id="code" placeholder="code">
            <label for="code">totp</label>
        </div>
        <button id="submit" class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
        <input type="hidden" name="csrf" value="`)
//line internal/templates/totp.qtpl:30
	qw422016.E().S(p.CsrfToken)
//line internal/templates/totp.qtpl:30
	qw422016.N().S(`"/>
    </form>
</main>
<script src="../../assets/js/bootstrap.bundle.min.js"></script>
<script>
    $('#submit').click( function(e) {
        //e.preventDefault()
        $('#form').submit();
    });
</script>
`)
//line internal/templates/totp.qtpl:40
}

//line internal/templates/totp.qtpl:40
func (p *Totp) WriteBody(qq422016 qtio422016.Writer) {
//line internal/templates/totp.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/totp.qtpl:40
	p.StreamBody(qw422016)
//line internal/templates/totp.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/totp.qtpl:40
}

//line internal/templates/totp.qtpl:40
func (p *Totp) Body() string {
//line internal/templates/totp.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/totp.qtpl:40
	p.WriteBody(qb422016)
//line internal/templates/totp.qtpl:40
	qs422016 := string(qb422016.B)
//line internal/templates/totp.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/totp.qtpl:40
	return qs422016
//line internal/templates/totp.qtpl:40
}
