// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line internal/template/basepage.qtpl:3
package template

//line internal/template/basepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/template/basepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/template/basepage.qtpl:4
type Page interface {
//line internal/template/basepage.qtpl:4
	Head() string
//line internal/template/basepage.qtpl:4
	StreamHead(qw422016 *qt422016.Writer)
//line internal/template/basepage.qtpl:4
	WriteHead(qq422016 qtio422016.Writer)
//line internal/template/basepage.qtpl:4
	Body() string
//line internal/template/basepage.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line internal/template/basepage.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line internal/template/basepage.qtpl:4
}

// Page prints a page implementing Page interface.

//line internal/template/basepage.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line internal/template/basepage.qtpl:12
	qw422016.N().S(`
<!doctype html>
<html>
`)
//line internal/template/basepage.qtpl:15
	p.StreamHead(qw422016)
//line internal/template/basepage.qtpl:15
	qw422016.N().S(`
	<body>
		<div>
			<a href="/">return to main page</a>
		</div>
		`)
//line internal/template/basepage.qtpl:20
	p.StreamBody(qw422016)
//line internal/template/basepage.qtpl:20
	qw422016.N().S(`
	</body>
</html>
`)
//line internal/template/basepage.qtpl:23
}

//line internal/template/basepage.qtpl:23
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line internal/template/basepage.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/template/basepage.qtpl:23
	StreamPageTemplate(qw422016, p)
//line internal/template/basepage.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line internal/template/basepage.qtpl:23
}

//line internal/template/basepage.qtpl:23
func PageTemplate(p Page) string {
//line internal/template/basepage.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/template/basepage.qtpl:23
	WritePageTemplate(qb422016, p)
//line internal/template/basepage.qtpl:23
	qs422016 := string(qb422016.B)
//line internal/template/basepage.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/template/basepage.qtpl:23
	return qs422016
//line internal/template/basepage.qtpl:23
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods

//line internal/template/basepage.qtpl:28
type BasePage struct{}

//line internal/template/basepage.qtpl:29
func (p *BasePage) StreamHead(qw422016 *qt422016.Writer) {
//line internal/template/basepage.qtpl:29
	qw422016.N().S(`This is a base head`)
//line internal/template/basepage.qtpl:29
}

//line internal/template/basepage.qtpl:29
func (p *BasePage) WriteHead(qq422016 qtio422016.Writer) {
//line internal/template/basepage.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/template/basepage.qtpl:29
	p.StreamHead(qw422016)
//line internal/template/basepage.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/template/basepage.qtpl:29
}

//line internal/template/basepage.qtpl:29
func (p *BasePage) Head() string {
//line internal/template/basepage.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/template/basepage.qtpl:29
	p.WriteHead(qb422016)
//line internal/template/basepage.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/template/basepage.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/template/basepage.qtpl:29
	return qs422016
//line internal/template/basepage.qtpl:29
}

//line internal/template/basepage.qtpl:30
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/template/basepage.qtpl:30
	qw422016.N().S(`This is a base body`)
//line internal/template/basepage.qtpl:30
}

//line internal/template/basepage.qtpl:30
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/template/basepage.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/template/basepage.qtpl:30
	p.StreamBody(qw422016)
//line internal/template/basepage.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line internal/template/basepage.qtpl:30
}

//line internal/template/basepage.qtpl:30
func (p *BasePage) Body() string {
//line internal/template/basepage.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/template/basepage.qtpl:30
	p.WriteBody(qb422016)
//line internal/template/basepage.qtpl:30
	qs422016 := string(qb422016.B)
//line internal/template/basepage.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/template/basepage.qtpl:30
	return qs422016
//line internal/template/basepage.qtpl:30
}
