// Code generated by qtc from "filelist.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line internal/template/filelist.qtpl:3
package template

//line internal/template/filelist.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/template/filelist.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/template/filelist.qtpl:4
type FileListPage struct {
	Files []FileMetadata
}

//line internal/template/filelist.qtpl:10
func (p *FileListPage) StreamHead(qw422016 *qt422016.Writer) {
//line internal/template/filelist.qtpl:10
	qw422016.N().S(`
<head>
    <title>File browsing</title>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="../../assets/css/filelist.css">
    <link rel="icon" href="data:,">
</head>
`)
//line internal/template/filelist.qtpl:19
}

//line internal/template/filelist.qtpl:19
func (p *FileListPage) WriteHead(qq422016 qtio422016.Writer) {
//line internal/template/filelist.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/template/filelist.qtpl:19
	p.StreamHead(qw422016)
//line internal/template/filelist.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line internal/template/filelist.qtpl:19
}

//line internal/template/filelist.qtpl:19
func (p *FileListPage) Head() string {
//line internal/template/filelist.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/template/filelist.qtpl:19
	p.WriteHead(qb422016)
//line internal/template/filelist.qtpl:19
	qs422016 := string(qb422016.B)
//line internal/template/filelist.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/template/filelist.qtpl:19
	return qs422016
//line internal/template/filelist.qtpl:19
}

//line internal/template/filelist.qtpl:21
func (p *FileListPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/template/filelist.qtpl:21
	qw422016.N().S(`
    `)
//line internal/template/filelist.qtpl:22
	streamlistFiles(qw422016, p.Files)
//line internal/template/filelist.qtpl:22
	qw422016.N().S(`
`)
//line internal/template/filelist.qtpl:23
}

//line internal/template/filelist.qtpl:23
func (p *FileListPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/template/filelist.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/template/filelist.qtpl:23
	p.StreamBody(qw422016)
//line internal/template/filelist.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line internal/template/filelist.qtpl:23
}

//line internal/template/filelist.qtpl:23
func (p *FileListPage) Body() string {
//line internal/template/filelist.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/template/filelist.qtpl:23
	p.WriteBody(qb422016)
//line internal/template/filelist.qtpl:23
	qs422016 := string(qb422016.B)
//line internal/template/filelist.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/template/filelist.qtpl:23
	return qs422016
//line internal/template/filelist.qtpl:23
}

//line internal/template/filelist.qtpl:25
func streamlistFiles(qw422016 *qt422016.Writer, files []FileMetadata) {
//line internal/template/filelist.qtpl:25
	qw422016.N().S(`
<table>
    <thead>
    <tr class="header" id="theader">
        <th id="nameColumnHeader" tabindex=0 role="button">Name</th>
        <th id="sizeColumnHeader" class="detailsColumn" tabindex=0 role="button">
            Size
        </th>
        <th id="typeColumnHeader" class="detailsColumn" tabindex=0 role="button">
            Type
        </th>
    </tr>
    <tbody id="tbody">
    `)
//line internal/template/filelist.qtpl:38
	for _, v := range files {
//line internal/template/filelist.qtpl:38
		qw422016.N().S(`
    <tr>
        <td data-value="eblo_antona">
            <a class="icon-file" draggable="true" href='`)
//line internal/template/filelist.qtpl:41
		qw422016.E().S(v.ID)
//line internal/template/filelist.qtpl:41
		qw422016.N().S(`'>`)
//line internal/template/filelist.qtpl:41
		qw422016.E().S(v.Name)
//line internal/template/filelist.qtpl:41
		qw422016.N().S(`</a>
        </td>
        <!-- TODO -h size display MB,KB,GB -->
        <td class="detailsColumn" data-value='`)
//line internal/template/filelist.qtpl:44
		qw422016.E().S(v.Size)
//line internal/template/filelist.qtpl:44
		qw422016.N().S(`'>`)
//line internal/template/filelist.qtpl:44
		qw422016.E().S(v.Size)
//line internal/template/filelist.qtpl:44
		qw422016.N().S(`</td>
        <td class="detailsColumn" data-value='`)
//line internal/template/filelist.qtpl:45
		qw422016.E().S(v.Type)
//line internal/template/filelist.qtpl:45
		qw422016.N().S(`'>`)
//line internal/template/filelist.qtpl:45
		qw422016.E().S(v.Type)
//line internal/template/filelist.qtpl:45
		qw422016.N().S(`</td>
    </tr>
    </tbody>
    `)
//line internal/template/filelist.qtpl:48
	}
//line internal/template/filelist.qtpl:48
	qw422016.N().S(`
    </thead>
</table>
`)
//line internal/template/filelist.qtpl:51
}

//line internal/template/filelist.qtpl:51
func writelistFiles(qq422016 qtio422016.Writer, files []FileMetadata) {
//line internal/template/filelist.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/template/filelist.qtpl:51
	streamlistFiles(qw422016, files)
//line internal/template/filelist.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line internal/template/filelist.qtpl:51
}

//line internal/template/filelist.qtpl:51
func listFiles(files []FileMetadata) string {
//line internal/template/filelist.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/template/filelist.qtpl:51
	writelistFiles(qb422016, files)
//line internal/template/filelist.qtpl:51
	qs422016 := string(qb422016.B)
//line internal/template/filelist.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/template/filelist.qtpl:51
	return qs422016
//line internal/template/filelist.qtpl:51
}
